// <auto-generated />
namespace WebBanHangAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class aassd112 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aassd112));
        
        string IMigrationMetadata.Id
        {
            get { return "202011240720219_aassd112"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
