// <auto-generated />
namespace WebBanHangAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class o12rt4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(o12rt4));
        
        string IMigrationMetadata.Id
        {
            get { return "202011161146020_o12rt4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
